# Funding — Adds a "Sponsor" button to the repo
# Docs: https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository

github: [stevegonsalves18]
# ko_fi: # your-ko-fi-username
# patreon: # your-patreon-username
# custom: ["https://your-link.com"]
