"""
Generate tool-specific adapter files from a shared manifest.

Canonical human-authored policy lives in:

- AGENTS.md
- scoped AGENTS.md files

This script only generates compatibility shims and tool-native loader files.

Run:

    python scripts/sync_agent_adapters.py
    python scripts/sync_agent_adapters.py --check

Ported from Universe Dex DevX Agent Infrastructure.
"""

from __future__ import annotations

import argparse
import json
import pathlib

ROOT = pathlib.Path(__file__).resolve().parent.parent
MANIFEST_PATH = ROOT / "scripts" / "agent_adapter_manifest.json"
GENERATED_NOTE = (
    "<!-- Generated by scripts/sync_agent_adapters.py from "
    "scripts/agent_adapter_manifest.json. Do not edit manually. -->"
)


def load_manifest() -> dict:
    return json.loads(MANIFEST_PATH.read_text(encoding="utf-8"))


def _lines(items: list[str]) -> str:
    return "\n".join(f"- {item}" for item in items)


def _cursor_yaml_list(items: list[str]) -> str:
    return "\n".join(f'  - "{item}"' for item in items)


def render_wrapper(path_name: str, repo_name: str, target: str) -> str:
    return "\n".join(
        [
            GENERATED_NOTE,
            f"# {path_name} - {repo_name}",
            "",
            f"@./{target}",
            "",
        ]
    )


def render_scoped_wrapper(path_name: str, repo_name: str, targets: list[str]) -> str:
    return "\n".join(
        [
            GENERATED_NOTE,
            f"# {path_name} - {repo_name}",
            "",
            *[f"@{target}" for target in targets],
            "",
        ]
    )


def render_cursorrules(lines: list[str]) -> str:
    return "\n".join(
        [
            GENERATED_NOTE,
            "# NexusHealth - Cursor Compatibility Shim",
            "",
            _lines(lines),
            "",
        ]
    )


def render_copilot_repo(repo_name: str, lines: list[str]) -> str:
    return "\n".join(
        [
            GENERATED_NOTE,
            f"# {repo_name} - Repository Instructions",
            "",
            _lines(lines),
            "",
        ]
    )


def render_copilot_scope(apply_to: str, lines: list[str]) -> str:
    return "\n".join(
        [
            "---",
            f'applyTo: "{apply_to}"',
            "---",
            GENERATED_NOTE,
            _lines(lines),
            "",
        ]
    )


def render_cursor_rule(description: str, globs: list[str], lines: list[str], refs: list[str]) -> str:
    body = [
        "---",
        f"description: {description}",
        "alwaysApply: false",
        "globs:",
        _cursor_yaml_list(globs),
        "---",
        GENERATED_NOTE,
        "",
        *lines,
        "",
        *[f"@{ref}" for ref in refs],
        "",
    ]
    return "\n".join(body)


def render_cursor_root_rule(description: str, lines: list[str], refs: list[str]) -> str:
    body = [
        "---",
        f"description: {description}",
        "alwaysApply: true",
        "---",
        GENERATED_NOTE,
        "",
        *lines,
        "",
        *[f"@{ref}" for ref in refs],
        "",
    ]
    return "\n".join(body)


def render_kiro_file(title: str, lines: list[str]) -> str:
    return "\n".join(
        [
            "---",
            "inclusion: always",
            "---",
            GENERATED_NOTE,
            "",
            f"# {title}",
            "",
            "- Canonical coding instructions live in AGENTS.md; also read the nearest scoped AGENTS.md before editing files.",
            "",
            _lines(lines),
            "",
        ]
    )


def build_generated_files(manifest: dict) -> dict[str, str]:
    files: dict[str, str] = {}
    repo_name = manifest["repo_name"]
    target = manifest["canonical_agents_file"]

    for wrapper in manifest["wrapper_files"]:
        files[wrapper] = render_wrapper(wrapper, repo_name, target)

    for wrapper in manifest.get("scoped_wrapper_files", []):
        files[wrapper["path"]] = render_scoped_wrapper(wrapper["path"], repo_name, wrapper["targets"])

    files[".cursorrules"] = render_cursorrules(manifest["cursor_legacy_shim_lines"])
    files[".github/copilot-instructions.md"] = render_copilot_repo(repo_name, manifest["copilot_repo_lines"])

    cursor_root = manifest["cursor_root_rule"]
    files[".cursor/rules/00-root.mdc"] = render_cursor_root_rule(
        cursor_root["description"],
        cursor_root["lines"],
        cursor_root["refs"],
    )

    for scope in manifest["scopes"]:
        files[f".github/instructions/{scope['id']}.instructions.md"] = render_copilot_scope(
            scope["copilot_apply_to"],
            scope["copilot_lines"],
        )
        files[f".cursor/rules/{scope['cursor_rule_file']}"] = render_cursor_rule(
            scope["cursor_description"],
            scope["cursor_globs"],
            scope["cursor_lines"],
            scope["cursor_refs"],
        )

    files[".kiro/steering/product.md"] = render_kiro_file("Product Overview", manifest["kiro"]["product"])
    files[".kiro/steering/tech.md"] = render_kiro_file("Technology Stack", manifest["kiro"]["tech"])
    files[".kiro/steering/structure.md"] = render_kiro_file("Project Structure", manifest["kiro"]["structure"])

    return files


def write_generated_files(files: dict[str, str]) -> None:
    for rel_path, content in files.items():
        path = ROOT / rel_path
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")


def remove_obsolete_files(manifest: dict) -> None:
    for rel_path in manifest.get("obsolete_files", []):
        path = ROOT / rel_path
        if path.exists():
            path.unlink()


def check_generated_files(files: dict[str, str]) -> list[str]:
    errors: list[str] = []
    for rel_path, expected in files.items():
        path = ROOT / rel_path
        if not path.exists():
            if _is_local_only_generated_file(rel_path):
                continue
            errors.append(f"missing generated file: {rel_path}")
            continue
        actual = path.read_text(encoding="utf-8")
        if actual != expected:
            errors.append(f"out-of-sync generated file: {rel_path}")
    return errors


def _is_local_only_generated_file(rel_path: str) -> bool:
    path = pathlib.PurePosixPath(rel_path)
    return (
        rel_path in {"CLAUDE.md", "GEMINI.md", ".cursorrules"}
        or path.parts[:1] in {(".cursor",), (".kiro",)}
    )


def check_obsolete_files(manifest: dict) -> list[str]:
    errors: list[str] = []
    for rel_path in manifest.get("obsolete_files", []):
        if (ROOT / rel_path).exists():
            errors.append(f"obsolete adapter file still present: {rel_path}")
    return errors


def _is_ignored_adapter_path(path: pathlib.Path) -> bool:
    ignored_parts = {
        ".git",
        ".next",
        ".pytest_cache",
        ".swc",
        "__pycache__",
        "node_modules",
        "playwright-report",
        "test-results",
    }
    return any(part in ignored_parts for part in path.parts)


def _adapter_candidates() -> set[str]:
    candidates: set[str] = set()

    for file_name in ("CLAUDE.md", "GEMINI.md"):
        for path in ROOT.rglob(file_name):
            if not _is_ignored_adapter_path(path.relative_to(ROOT)):
                candidates.add(path.relative_to(ROOT).as_posix())

    for rel_path in (".cursorrules", ".github/copilot-instructions.md"):
        if (ROOT / rel_path).exists():
            candidates.add(rel_path)

    for pattern in (
        ".github/instructions/*.instructions.md",
        ".cursor/rules/*.mdc",
        ".kiro/steering/*.md",
    ):
        for path in ROOT.glob(pattern):
            candidates.add(path.relative_to(ROOT).as_posix())

    return candidates


def check_unmanaged_adapter_files(generated_files: dict[str, str], manifest: dict) -> list[str]:
    expected = {pathlib.PurePosixPath(path).as_posix() for path in generated_files}
    obsolete = {pathlib.PurePosixPath(path).as_posix() for path in manifest.get("obsolete_files", [])}
    unmanaged = sorted(_adapter_candidates() - expected - obsolete)
    return [f"unmanaged adapter file: {path}" for path in unmanaged]


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description="NexusHealth - Sync agent adapter files from manifest."
    )
    parser.add_argument("--check", action="store_true", help="Verify generated files are in sync.")
    args = parser.parse_args(argv)

    manifest = load_manifest()
    files = build_generated_files(manifest)

    if args.check:
        errors = check_generated_files(files)
        errors.extend(check_obsolete_files(manifest))
        errors.extend(check_unmanaged_adapter_files(files, manifest))
        if errors:
            print("Agent adapter sync: FAIL")
            for error in errors:
                print(f" - {error}")
            return 1
        print("Agent adapter sync: PASS")
        print(f" - generated files in sync: {len(files)}")
        return 0

    write_generated_files(files)
    remove_obsolete_files(manifest)
    print("Agent adapter sync: WROTE")
    print(f" - generated files written: {len(files)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
