import pytest

from backend import auth, models


def _registry_module():
    try:
        from backend import ai_function_registry
    except ImportError:
        pytest.fail("backend.ai_function_registry module is required for AI governance inventory")
    return ai_function_registry


def _create_user(db_session, username: str, role: str) -> models.User:
    user = models.User(
        username=username,
        email=f"{username}@example.com",
        hashed_password=auth.get_password_hash("StrongPassword123!"),
        role=role,
    )
    db_session.add(user)
    db_session.commit()
    db_session.refresh(user)
    return user


def _auth_headers(username: str) -> dict[str, str]:
    return {"Authorization": f"Bearer {auth.create_access_token({'sub': username})}"}


def test_ai_registry_contains_required_clinical_controls():
    registry = _registry_module()

    functions = registry.list_ai_functions()
    function_ids = {function["id"] for function in functions}

    assert {
        "clinical_chat",
        "streaming_clinical_chat",
        "risk_prediction",
        "prediction_explanation",
        "lab_report_analysis",
        "health_report_generation",
    }.issubset(function_ids)
    for function in functions:
        if function["clinical_safety_required"]:
            assert function["medical_disclaimer_required"] is True
            assert function["human_review_required"] is True
            assert function["basis_transparency_required"] is True
        if function["uses_ai_provider"]:
            assert function["provider_boundary"] == "backend.core_ai"


def test_ai_registry_validation_rejects_duplicate_ids():
    registry = _registry_module()
    function = registry.AIFunction(
        id="duplicate",
        name="Duplicate",
        module="backend.example",
        endpoints=("/example",),
        audience=("doctor",),
        risk_category="clinical_support",
        clinical_safety_required=True,
        medical_disclaimer_required=True,
        human_review_required=True,
        basis_transparency_required=True,
        uses_ai_provider=True,
        provider_boundary="backend.core_ai",
        prompt_keys=(),
    )

    with pytest.raises(registry.AIRegistryError, match="Duplicate AI function id"):
        registry.validate_ai_registry((function, function))


def test_medical_disclaimer_detection_accepts_approved_disclaimer_language():
    registry = _registry_module()

    assert registry.contains_medical_disclaimer(
        "Please consult a qualified healthcare professional for medical decisions or emergencies."
    )
    assert registry.contains_medical_disclaimer(
        "Please consult a qualified clinician for diagnosis, treatment, or emergencies."
    )
    assert not registry.contains_medical_disclaimer("This result is generated by AI.")


def test_admin_lists_ai_function_registry(client, db_session):
    admin = _create_user(db_session, "ai_registry_admin", "admin")

    response = client.get("/admin/ai-functions", headers=_auth_headers(admin.username))

    assert response.status_code == 200
    payload = response.json()
    assert payload["source"] == "backend.ai_function_registry"
    assert "WHO AI governance" in payload["governance_anchors"]
    assert any(function["id"] == "clinical_chat" for function in payload["functions"])
    assert all("provider_api_key" not in function for function in payload["functions"])


def test_patient_cannot_list_ai_function_registry(client, db_session):
    patient = _create_user(db_session, "ai_registry_patient", "patient")

    response = client.get("/admin/ai-functions", headers=_auth_headers(patient.username))

    assert response.status_code == 403
    assert response.json()["detail"] == "Admin privileges required"
